### ISSUE TITLE
Linked Collections are not converted

### ISSUE THREAD

**Issue by fdplacido** [key4hep/k4LCIOReader#10]
I created a test in k4MarlinWrapper to test conversion of collections from EDM4hep to LCIO to EDM4hep.
When converting Tracks, these can have other Tracks linked to it. I test that these linked Tracks remain in the conversion between EDM4hep to LCIO.
But when converting from LCIO to EDM4hep these linked Tracks are missing in the resulting EDM4hep collection. This is probably true for other collections that have linked collections.

The conversion is done using k4LCIOConverter like so:

```cpp
podio::CollectionIDTable* id_table = new podio::CollectionIDTable();
k4LCIOConverter* lcio_converter = new k4LCIOConverter(id_table);
lcio_converter->set(the_event);

T* mycoll = dynamic_cast<T*>(lcio_converter->getCollection(lcio_name));
```

**Comment by zoujh** [comment]
Hi @fdplacido , is it possible to send me (zoujh@ihep.ac.cn) such a data sample? It's important to reproduce the problem for debugging. Thanks!

**Comment by fdplacido** [comment]
I sent you the data sample and some info. Thanks!

**Comment by zoujh** [comment]
If object A and B are in the same collection, then A cannot  be linked to B correctly. This should be fix in  this [commit](https://github.com/key4hep/k4LCIOReader/commit/692861f20efadf9e5b2f69f85a174d1589354091). Thank you!

**Comment by fdplacido** [comment]
I tested this and it works fine now, thank!
