### ISSUE TITLE
Rename and move repository

### ISSUE THREAD

**Issue by andresailer** [key4hep/k4LCIOReader#4]
@zoujh as a member of the key4hep project you should be able to create new repositories there. So this should mean you could move this repository there already.

**Comment by mirguest** [comment]
Hi @andresailer 
I transfer this repo from ihep-sft-group to key4hep now.
Tao

**Comment by mirguest** [comment]
Hi @andresailer and @zoujh ,
After clicking transfer in the repo setting, I am not the admin any more. Could you rename the repo?
Tao

**Comment by vvolkl** [comment]
Hi @mirguest,

I renamed this to k4LCIOReader and added you as admin.

**Comment by mirguest** [comment]
Thank you @vvolkl 
Tao

**Comment by mirguest** [comment]
Fix in PR #5
